input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  if ![timestamp] {
    mutate {
      add_field => { "timestamp" => "%{@timestamp}" }
    }
  }

  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }

  mutate {
    lowercase => ["event_type", "stream_type", "system"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[target_index]}"
  }

  stdout {
    codec => rubydebug
  }
}
